import { Product, Category } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  // QUICK PRODUCTS (Fast Selling)
  {
    id: "m1",
    barcode: "",
    name: "Lait en Sachet (Colombe)",
    price: 25,
    stock: 500,
    category: Category.DAIRY,
    unit: "unit",
    isQuick: true,
  },
  {
    id: "b1",
    barcode: "",
    name: "Baguette Pain Blanc",
    price: 15,
    stock: 1000,
    category: Category.BAKERY,
    unit: "unit",
    isQuick: true,
  },
  {
    id: "b2",
    barcode: "",
    name: "Pain Matlou3",
    price: 35,
    stock: 200,
    category: Category.BAKERY,
    unit: "unit",
    isQuick: true,
  },
  {
    id: "e1",
    barcode: "",
    name: "Oeufs (Unité)",
    price: 18,
    stock: 1500,
    category: Category.DAIRY,
    unit: "unit",
    isQuick: true,
  },
  {
    id: "e2",
    barcode: "",
    name: "Plateau d'Oeufs (30)",
    price: 520,
    stock: 50,
    category: Category.DAIRY,
    unit: "plate",
    isQuick: true,
  },
  {
    id: "w1",
    barcode: "",
    name: "Ifri Eau 5L",
    price: 130,
    stock: 80,
    category: Category.DRINKS,
    unit: "unit",
    isQuick: true,
  },

  // BRANDS / BARCODED
  {
    id: "1",
    barcode: "6130001001",
    name: "Selecto 1.5L",
    price: 135,
    stock: 45,
    category: Category.DRINKS,
    image: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "2",
    barcode: "6130001002",
    name: "Ifri 1.5L",
    price: 45,
    stock: 120,
    category: Category.DRINKS,
    image: "https://images.unsplash.com/photo-1548919973-5dea58b665e9?q=80&w=200&auto=format&fit=crop",
  },
  {
    id: "h1",
    barcode: "6130001003",
    name: "Hamoud White 1L",
    price: 110,
    stock: 60,
    category: Category.DRINKS,
  },
  {
    id: "r1",
    barcode: "6130001004",
    name: "Rouiba Orange 1L",
    price: 160,
    stock: 40,
    category: Category.DRINKS,
  },

  // DAILY ESSENTIALS
  {
    id: "s1",
    barcode: "6130003003",
    name: "Sucre Baguette 1kg",
    price: 105,
    stock: 100,
    category: Category.GROCERY,
    isQuick: true,
  },
  {
    id: "o1",
    barcode: "6130003004",
    name: "Huile Elio 5L",
    price: 650,
    stock: 30,
    category: Category.GROCERY,
    isQuick: true,
  },
  {
    id: "c1",
    barcode: "6130003005",
    name: "Café Facto 250g",
    price: 320,
    stock: 50,
    category: Category.GROCERY,
  },

  // FRUITS & VEGGIES (Weight based)
  {
    id: "fv1",
    barcode: "",
    name: "Pommes de Terre",
    price: 85,
    stock: 200,
    category: Category.FRUITS_VEGGIES,
    unit: "kg",
    isQuick: true,
  },
  {
    id: "fv2",
    barcode: "",
    name: "Oignons",
    price: 70,
    stock: 150,
    category: Category.FRUITS_VEGGIES,
    unit: "kg",
    isQuick: true,
  },
  {
    id: "fv3",
    barcode: "",
    name: "Tomates",
    price: 120,
    stock: 100,
    category: Category.FRUITS_VEGGIES,
    unit: "kg",
    isQuick: true,
  },
  {
    id: "fv4",
    barcode: "",
    name: "Bananes",
    price: 450,
    stock: 50,
    category: Category.FRUITS_VEGGIES,
    unit: "kg",
  },

  // BULK / WEIGHT
  {
    id: "ol1",
    barcode: "",
    name: "Olives Vertes (Poids)",
    price: 600,
    stock: 20,
    category: Category.GROCERY,
    unit: "kg",
  },
  {
    id: "ol2",
    barcode: "",
    name: "Olives Noires (Poids)",
    price: 750,
    stock: 15,
    category: Category.GROCERY,
    unit: "kg",
  },
  {
    id: "hw1",
    barcode: "",
    name: "Halwa Turc 250g",
    price: 380,
    stock: 40,
    category: Category.GROCERY,
    isQuick: true,
  },
  {
    id: "ch1",
    barcode: "",
    name: "Fromage Portion 16p",
    price: 240,
    stock: 60,
    category: Category.DAIRY,
    isQuick: true,
  },
  {
    id: "ch2",
    barcode: "",
    name: "Camembert local",
    price: 180,
    stock: 30,
    category: Category.DAIRY,
  },
  {
    id: "sem1",
    barcode: "",
    name: "Semoule Mama 1kg",
    price: 120,
    stock: 100,
    category: Category.GROCERY,
  },
  {
    id: "oe1",
    barcode: "",
    name: "Huile de Table 1L",
    price: 125,
    stock: 80,
    category: Category.GROCERY,
  },
];

export const MOCK_CREDITS = [
  {
    id: "cr1",
    customerName: "Mohamed Amine",
    date: new Date().toISOString(),
    total: 1450.00,
    sequentialId: 101,
    ticketId: "TKT-00101",
    items: [
      { id: "1", name: "Selecto 1.5L", price: 135, quantity: 2, stock: 45, category: "Drinks", barcode: "6130001001" },
      { id: "s1", name: "Sucre Baguette 1kg", price: 105, quantity: 5, stock: 100, category: "Grocery", barcode: "6130003003" }
    ]
  },
  {
    id: "cr2",
    customerName: "Youcef Bou",
    date: new Date(Date.now() - 86400000).toISOString(),
    total: 3200.00,
    sequentialId: 98,
    ticketId: "TKT-00098",
    items: [
      { id: "o1", name: "Huile Elio 5L", price: 650, quantity: 4, stock: 30, category: "Grocery", barcode: "6130003004" }
    ]
  }
];
